version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: keaiduo1
    volumes:
      - "/var/docker/${repository}/data:/var/lib/mysql"
      - "/var/docker/${repository}/log:/var/log/mysqld"
      - "/var/docker/${repository}/run:/var/run/mysqld"
    networks:
      - ${repository}net
networks:
  ${repository}net:
    name: ${repository}net
